name: Haxe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        haxe: [4.2.3, 3.4.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe  }}
      - run: haxe -v
      
      - name: Build
        run: |
          haxe --main Main --neko hello.n
          haxe --hl hello.hl --main Main
      - name: Test-neko
        run: neko hello.n
      - name: Test-hashlink
        run: hl hello.hl
      - name: Test-interpreter
        run: haxe --interp --main Main
      - name: Test-haxeproject
        run: haxe build.hxml
