name: Haxe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Haxe setup
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
      - name: Hashlink setup
        uses: pxshadow/setup-hashlink@v1.0.1
        
      - name: haxe version
        run: haxe -v
      - name: hashlink version
        run: hl
      
      - name: Build
        run: |
          haxe --main Main --neko hello.n
          haxe --hl hello.hl --main Main
      - name: Test-neko
        run: neko hello.n
      - name: Test-hashlink
        run: hl hello.hl
      - name: Test-interpreter
        run: haxe --interp --main Main
      - name: Test-haxeproject
        run: haxe build.hxml
