name: Julia

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: julia setup
        uses: julia-actions/setup-julia@v1
        with:
          version: 1
          arch: arch
          
      - name: Test
        run: julia hello.jl
