name: smalltalk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deps
        run: sudo apt-get install gnu-smalltalk
      - name: smalltalk version
        run: gst -v
      - name: run
        run: gst hello.st
